version: '3.8'

services:
  twitchviewer:
    build:
      context: .
      dockerfile: Dockerfile
    image: twitchviewer:latest
    container_name: twitchviewer
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      # Hassas bilgileri buraya doğrudan yazma, .env dosyası veya Docker Secrets kullan
      - DATABASE_URL=${DATABASE_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - VITE_STRIPE_PUBLIC_KEY=${VITE_STRIPE_PUBLIC_KEY}
      - SESSION_SECRET=${SESSION_SECRET}
    # Sağlık kontrolü
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      
  # PostgreSQL ekleme - Gelişmiş ortamlar için
  # db:
  #   image: postgres:15-alpine
  #   container_name: twitchviewer-db
  #   restart: unless-stopped
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=twitchviewer
  #   ports:
  #     - "5432:5432"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3

# PostgreSQL data volume
# volumes:
#   db_data: